### ISSUE TITLE
NBT tag support.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#2]
@RealizedMC Would it be possible to add NBT tagging support for item displays? I mainly would like it to add the Unbreakable NBT tag to an item since my resource pack has custom item textures for items with specific damage values and an unbreakable nbt tag on it.

https://minecraft.gamepedia.com/Tutorials/Command_NBT_tags

It would also be nice to set glow effect on an item without an enchant or enchant an item and hide all tags.

**Comment by Realizedd** [comment]
Added the option 'unbreakable:true' for shop items in 3407c06

**Comment by mibby** [comment]
@RealizedMC Where would I put it in the config, assuming it is functioning as intended? I did the following but I still do not see the item in the shop.

```
      '16':
        displayed: 277:117 1 name:&bCrown_Hat lore:&dCost:&a_32_Tokens
        cost: 32
        confirm-purchase: true
        unbreakable: true
        message: '&b&lToken &f&l» &7Purchase completed, %player%! &c-32 tokens'
        commands:
        - 'mgive %player% hat_pvpcrown 1'
```

What it looks like in the GUI shop.
![link](https://i.imgur.com/9th2eDC.png)

What it looks like in-game when held - a specific durability shovel with unbreakable nbt tag set.
![link2](https://i.imgur.com/cLB4Bfb.png)

Paper dev 1386 (Spigot 1.12.2)
TokenManager v3.0.3
