### ISSUE TITLE
TokenManager placeholder slow update rate?

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#21]
Hi @RealizedMC,

Using the TokenManager PlaceholderAPI expansion (v2.0.8), I noticed ```%tokenmanager_tokens%``` in my menu GUI takes a minute or two to actually update and reflect the person's balance. It displays ```0``` until it actually grabs their true balance value. 

I was wondering, is this a problem with the TokenManager placeholder having a slow update interval or is it a symptom of the BossShop gui being slow to update? The GUI correctly updates the player's economy and points balance fast as soon as they open the gui, just not tokens until it is actually cached a minute or two after opening the gui.

**Comment by Realizedd** [comment]
Use my own implementation instead: `%tm_tokens%`

**Comment by mibby** [comment]
@RealizedMC ```%tm_tokens%``` doesn't seem to return anything. It just displays text. For reference, I'm using the placeholder in another plugin's GUI as a main menu to display balance.

**Comment by Realizedd** [comment]
Could you check if PlaceholderAPI says that the placeholder is registered?

**Comment by Realizedd** [comment]
I've just tested the placeholder with the latest version of [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) and [DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/), and it seems to work just fine.

**Comment by mibby** [comment]
How do I check if PAPI says the placeholder is registered?

```/papi info %tm_tokens%``` says no expansion was loaded with the identifier: %tm_tokens%. Is there a separate expansion to use or hook I have to enable within TokenManager? Or perhaps do you think having the TokenManager PAPI expansion installed disables your built-in one?

**Comment by Realizedd** [comment]
I'm not sure, but try removing the expansion and see if `/papi parse %tm_tokens%` works.

**Comment by mibby** [comment]
Removed the expansion and restarted the server, ```/papi parse %tm_tokens%``` still does not work for me. Just returns ```%tm_tokens%``` in text.

TokenManager v3.1.0
PlaceholderAPI v2.8.7
Paper dev 1437 (Spigot 1.12.2)

PAPI config;
```
check_updates: false
cloud_enabled: true
cloud_allow_unverified_expansions: false
boolean:
  'true': 'yes'
  'false': 'no'
date_format: MM/dd/yy HH:mm:ss
injector_enabled: true
expansions:
  vault:
    formatting:
      thousands: k
      trillions: T
      quadrillions: Q
      billions: B
      millions: M
  bungee:
    check_interval: 30
  javascript:
    engine: javascript
```

TokenManager is using MySQL database, redis false, online mode: true and register-economy: false.
