### ISSUE TITLE
Unbreakable NBT stopped working.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#23]
TokenManager v3.1.3
Paper dev 1536 (Spigot 1.12.2)

@RealizedMC It seems you broke the NBT ```unbreakable: true``` flag in one of the newer TokenManager versions. My shop no longer displays custom items with the unbreakable flag. :(

```
      '15':
        displayed: DIAMOND_SPADE:135 1 flags:HIDE_UNBREAKABLE,HIDE_ATTRIBUTES,HIDE_ENCHANTS name:&bSlouchy_Beanie_Hat lore:&dCost:&a_32_Tokens unbreakable:true
        cost: 32
        message: '&b&lToken &f&l» &7Purchase completed, %player%! &c-32 tokens'
        commands:
        - 'mgive %player% hat_slouchybeanie 1'
```

**Comment by mibby** [comment]
Upon further testing, it seems the order is now important?

```
      '16':
        displayed: DIAMOND_SPADE:103 1 unbreakable:true flags:HIDE_UNBREAKABLE,HIDE_ATTRIBUTES,HIDE_ENCHANTS name:&bWelder_Hat lore:&dCost:&a_32_Tokens
        cost: 32
        message: '&b&lToken &f&l» &7Purchase completed, %player%! &c-32 tokens'
        commands:
        - 'mgive %player% hat_welder 1'
```

Putting unbreakable:true before flags lets it work as intended.
