### ISSUE TITLE
Name colors are not updating correctly.

### ISSUE THREAD

**Issue by mibby** [Realizedd/TokenManager#26]
TokenManager 3.1.3
Paper dev 488 (Spigot 1.13.2)

@Realizedd Name colors don't seem to be updating correctly. Possibly a 1.13 issue?

```
      '4':
        displayed: TRIPWIRE_HOOK 1 unbreaking:10 flags:HIDE_UNBREAKABLE,HIDE_ATTRIBUTES,HIDE_ENCHANTS name:&f&lSuit_&6&lCrate_Key lore:&dCost:&a_%price%_Tokens
        cost: 40
        message: '&b&lToken &f&l» &7Purchase completed, %player%! &c-%price% tokens'
        commands:
        - 'cr give to %player% SuitCrate 1'
```

![link](https://i.imgur.com/CU6pWxB.png)

Should be white and bolded, not blue and italicized.
